<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2020-7-24
 * Time: 11:26
 */

namespace app\admin\controller;


use Payment\Client;
use Payment\Exceptions\ClassNotFoundException;
use Payment\Exceptions\GatewayException;
use think\Controller;
use think\Exception;

class Alipay extends Controller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index(){
        $peizhi = config('alipay');
        // 交易信息
        $tradeNo = time() . rand(1000, 9999);
        $payData = [
            'body'         => 'ali web pay',
            'subject'      => '测试支付宝电脑网站支付',
            'trade_no'     => $tradeNo,
            'time_expire'  => time() + 600, // 表示必须 600s 内付款
            'amount'       => '0.01', // 单位为元 ,最小为0.01
            'return_param' => '123123',
            // 'client_ip' => isset($_SERVER['REMOTE_ADDR']) ? $_SERVER['REMOTE_ADDR'] : '127.0.0.1',// 客户地址
            'goods_type' => '1', // 0—虚拟类商品，1—实物类商品
            'store_id'   => '',
        ];

        try {
            $client = new Client(Client::ALIPAY, $peizhi);
            $res    = $client->pay(Client::ALI_CHANNEL_WEB, $payData);
        } catch (\InvalidArgumentException $e) {
            echo $e->getMessage();
            exit;
        } catch (GatewayException $e) {
            echo $e->getMessage();
            var_dump($e->getRaw());
            exit;
        } catch (ClassNotFoundException $e) {
            echo $e->getMessage();
            exit;
        } catch (Exception $e) {
            echo $e->getMessage();
            exit;
        }
        return header('Location:' . $res);
    }

    /**
     * @return array
     */
    public function test()
    {
        $p = $this->request->param();
        $from = $p['from'];
        if ($from === 'ali') {
            $config = config('alipay');
            $proxy = Client::ALIPAY;
        } elseif ($from === 'wx') {
            $config = config('wxpay');
            $proxy  = Client::WECHAT;
        } else {
            $config = config('alipay');
            $proxy = Client::ALIPAY;
        }

        $callback = new TestNotify();

        try {
            $client = new Client($proxy, $config);
            $xml    = $client->notify($callback);
        } catch (\InvalidArgumentException $e) {
            echo $e->getMessage();
            exit;
        } catch (GatewayException $e) {
            echo $e->getMessage();
            exit;
        } catch (ClassNotFoundException $e) {
            echo $e->getMessage();
            exit;
        } catch (Exception $e) {
            echo $e->getMessage();
            exit;
        }

        var_dump($xml);
    }
}