<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/11/6
 * Time: 15:15
 */

namespace app\admin\controller;

use app\admin\model\HomeItem as ItemModel;

class HomeItem extends Admin
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->index_tab = config('other.index_tab');
        $this->assign('index_tab', $this->index_tab);
    }
    public function index($q = '')
    {
        if ($this->request->isAjax()) {
            $where = $data = [];
            $page = input('param.page/d', 1);
            $limit = input('param.limit/d', 20);

            $cat_id = input('param.cat_id/d');
            if ($cat_id){
                $where['cat_id'] = $cat_id;
            }
            $title = input('param.title');
            if ($title) {
                $where['title'] = ['like', "%{$title}%"];
            }
            $where['cid'] = session('admin_user.cid');
            $data['data'] = ItemModel::with('cat')->where($where)->page($page)->limit($limit)->select();
            if ($data['data']){
                foreach ($data['data'] as $k=>$v){
                    $v['cat_id'] = $this->index_tab[$v['cat_id']]['title'];
                }
            }
            $data['count'] = ItemModel::where($where)->count('id');
            $data['code'] = 0;
            $data['msg'] = '';
            return json($data);
        }
        return $this->fetch();
    }

    public function add()
    {
        if ($this->request->isPost()) {
            $data = $this->request->post();
            // 验证
            $result = $this->validate($data, 'HomeItem');
            if ($result !== true) {
                return $this->error($result);
            }
            $data['cid'] = session('admin_user.cid');
            $data['user_id'] = session('admin_user.uid');
            unset($data['id']);
            if (1 == $data['is_push']){
                if (empty($data['tuijian'])){
                    return $this->error('推荐位图片必填！');
                }
            }
            if (!ItemModel::create($data)) {
                return $this->error('添加失败！');
            }
            return $this->success('添加成功。', url('index'));
        }
        return $this->fetch('form');
    }

    public function edit($id = 0)
    {
        if ($this->request->isPost()) {
            $data = $this->request->post();
            // 验证
            $result = $this->validate($data, 'HomeItem');
            if ($result !== true) {
                return $this->error($result);
            }
            $data['cid'] = session('admin_user.cid');
            $data['user_id'] = session('admin_user.uid');
            if (1 == $data['is_push']){
                if (empty($data['tuijian'])){
                    return $this->error('推荐位图片必填！');
                }
            }
            if (!ItemModel::update($data)) {
                return $this->error('修改失败！');
            }
            return $this->success('修改成功。', url('index'));
        }

        $row = ItemModel::where('id', $id)->find()->toArray();
        $row['content'] = htmlspecialchars_decode($row['content']);
        $this->assign('data_info', $row);
        return $this->fetch('form');
    }

    public function delItem()
    {
        $id = input('param.id/a');
        $model = new ItemModel();
        if (!$model->del($id)) {
            return $this->error($model->getError());
        }
        return $this->success('删除成功');
    }

}