<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2020-9-10
 * Time: 17:44
 */

namespace app\admin\controller;


class Multifunctional extends Admin
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index(){
        return $this->fetch();
    }

}