<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/4/15
 * Time: 18:13
 */

namespace app\admin\controller;


use PhpAmqpLib\Connection\AMQPStreamConnection;
use PhpAmqpLib\Message\AMQPMessage;
use think\Controller;

class Rabbit extends Controller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function publisher(){
        $connection = new AMQPStreamConnection('localhost','5672','guest','guest');
        $channel = $connection->channel();
        $channel->queue_declare('hello',false,false,false,false);
        $msg = new AMQPMessage('Hello Word');
        $channel->basic_publish($msg,'','hello');
        $channel->close();
        $connection->close();
    }

    public function customer()
    {
        $connection = new AMQPStreamConnection('localhost','5672','guest','guest');
        $channel = $connection->channel();
        $channel->queue_declare('hello',false,false,false,false);
        $callback = function ($msg){
            echo $msg->body;
        };
        $channel->basic_consume('hello','',false,true,false,false,$callback);
        while (count($channel->callbacks)){
            $channel->wait();
        }
    }

}