<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/10/8
 * Time: 14:59
 */

namespace app\admin\controller;
use app\index\model\GgzyList;
use app\index\model\GgzyDetail;
use app\admin\model\Region;

class Resources extends Admin{
    public function _initialize()
    {
        return parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        if ($this->request->isAjax()) {
            $where = $data = [];
            $page = input('param.page/d', 1);
            $limit = input('param.limit/d', 20);

            $cat_id = input('param.cat_id/d');
            if ($cat_id) {
                $where['cat_id'] = $cat_id;
            }
            $title = input('param.title');
            if ($title) {
                $where['title'] = ['like', "%{$title}%"];
            }
            $s_status = input('param.s_status/d');
            if ($s_status) {
                $where['s_status'] = $s_status;
            }
            $order = 'status desc,id desc';
            $data['data'] = GgzyList::where($where)->page($page)->order($order)->limit($limit)->select();
            $data['count'] = GgzyList::where($where)->count('id');
            $data['code'] = 0;
            $data['msg'] = '';
            return json($data);
        }
        $this->assign('province', Region::getProvince());
        return $this->fetch();
    }

    public function read($id = 0)
    {
        $params = $this->request->param();
        $tab_data = [];
        $tab_data['menu'] = [
            [
                'title' => "招标/资审公告",
                'url' => "admin/resources/read",
                'params' => ['id'=>$id,'atype' => '0101'],
            ],
            [
                'title' => "开标记录",
                'url' => "admin/resources/read",
                'params' => ['id'=>$id,'atype' => '0102'],
            ],
            [
                'title' => "交易结果公示",
                'url' => "admin/resources/read",
                'params' => ['id'=>$id,'atype' => '0104'],
            ],
            [
                'title' => "招标/资审文件澄清",
                'url' => "admin/resources/read",
                'params' => ['id'=>$id,'atype' => '0105'],
            ],
        ];
        $tab_data['current'] = url('read', ['id'=>$id,'atype' => '0101']);

//        $field = 'region_code,type,pub_time';
        $data = GgzyDetail::where('list_id', 4)->order('pub_time desc')->select();
        $res = [];
        if ($data){
            foreach ($data as $k=>$v) {
                $res[$v['type']][$k] = $v;
            }
        }

        $this->assign('tab_data', $tab_data);
        $this->assign('tab_type', 1);
        $this->assign('isparams', 1);
        $this->assign('atype', $params['atype']);
        $this->assign('tab_url', url('read', ['id'=>$id,'atype' => $params['atype']]));
        $this->assign('data_info', $res);
        return $this->fetch();
    }
}