<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2020-11-18
 * Time: 17:46
 */

namespace app\admin\controller;


use think\Controller;

class Wework extends Controller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function test(){
        $wx_config = config('wework');
// 需启用 "管理工具" -> "通讯录同步", 并使用该处的secret, 才能通过API管理通讯录
//
        print_r($wx_config);exit();
        $api = new CorpAPI($wx_config['CORP_ID'], $wx_config['CONTACT_SYNC_SECRET']);


        try {
            //
            $user = new User();
            {
                $user->userid = "userid";
                $user->name = "name";
                $user->mobile = "131488888888";
                $user->email = "sbzhu@ipp.cas.cn";
                $user->department = array(1);

                $ExtattrList = new ExtattrList();
                $ExtattrList->attrs = array(new ExtattrItem("s_a_2", "aaa"), new ExtattrItem("s_a_3", "bbb"));
                $user->extattr = $ExtattrList;
            }
            $api->UserCreate($user);

            //
            $user = $api->UserGet("userid");
            var_dump($user);

            //
            $user->mobile = "1219887219873";
            $api->UserUpdate($user);

            //
            $userList = $api->userSimpleList(1, 0);
            var_dump($userList);

            //
            $userList = $api->UserList(1, 0);
            var_dump($userList);

            //
            $openId = null;
            $api->UserId2OpenId("ZhuShengBen", $openId);
            echo "openid: $openId\n";

            //
            $userId = null;
            $api->openId2UserId($openId, $userId);
            echo "userid: $userId\n";

            //
            $api->UserAuthSuccess("userid");

            //
            $api->UserBatchDelete(array("userid", "aaa"));

            //
            $api->UserDelete("userid");
        } catch (Exception $e) {
            echo $e->getMessage() . "\n";
            $api->UserDelete("userid");
        }

    }
}