<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/10/8
 * Time: 14:59
 */

namespace app\admin\controller;
use app\admin\model\SubjectCat as CatModel;
use app\admin\model\Xiangmu as XiangmuModel;
use app\admin\model\Project as ProjectModel;


class Xiangmu extends Admin{
    public function _initialize()
    {
        return parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        if ($this->request->isAjax()) {
            $where = $data = [];
            $page = input('param.page/d', 1);
            $limit = input('param.limit/d', 20);

            $cat_id = input('param.cat_id/d');
            if ($cat_id) {
                $where['cat_id'] = $cat_id;
            }
            $name = input('param.name');
            if ($name) {
                $where['name'] = ['like', "%{$name}%"];
            }
            $s_status = input('param.s_status/d');
            if ($s_status) {
                $where['s_status'] = $s_status;
            }
            $where['cid'] = session('admin_user.cid');
            $order = 'status desc,id desc';
            $data['data'] = XiangmuModel::with('cat')->where($where)->page($page)->order($order)->limit($limit)->select();
            $data['count'] = XiangmuModel::where($where)->count('id');
            $data['code'] = 0;
            $data['msg'] = '';
            return json($data);
        }


        $this->assign('cat_option', XiangmuModel::getOption());
        return $this->fetch();
    }

    public function add()
    {
        if ($this->request->isPost()) {
            $data = $this->request->post();
            $data['cid'] = session('admin_user.cid');
            $data['user_id'] = session('admin_user.uid');
            unset($data['id']);
            // 验证
            $result = $this->validate($data, 'Xiangmu');
            if ($result !== true) {
                return $this->error($result);
            }
            if (!XiangmuModel::create($data)) {
                return $this->error('添加失败');
            }
                return $this->success("操作成功{$this->score_value}");
        }
        $this->assign('subject_option', XiangmuModel::getOption(null));
        $this->assign('p_source', XiangmuModel::getPsource());
        $this->assign('three_level', XiangmuModel::getThreeLevel());
        $this->assign('grade_type', ProjectModel::getGrade());
        $this->assign('cur_time', date('YmdHis'));
        $this->assign('s_status', XiangmuModel::getSStatus(1));
        return $this->fetch('form');
    }

    public function edit($id = 0)
    {
        $row = XiangmuModel::where('id', $id)->find()->toArray();
        if ($this->request->isPost()) {
            $data = $this->request->post();
            $data['cid'] = session('admin_user.cid');
            $data['user_id'] = session('admin_user.uid');
            // 验证
            $result = $this->validate($data, 'Xiangmu');
            if ($result !== true) {
                return $this->error($result);
            }
            if (!XiangmuModel::update($data)) {
                return $this->error('修改失败');
            }
            return $this->success('修改成功');
        }

        if ($row){
            if (!empty($row['attachment'])){
                $attachment = explode(',',$row['attachment']);
                $row['attachment_show'] = array_filter($attachment);
            }
        }
//        print_r($row);
        $this->assign('cur_time', empty($row['idcard']) ? date('YmdHis') : $row['idcard']);
        $this->assign('data_info', $row);
        $this->assign('subject_option', XiangmuModel::getOption($row['cat_id']));
        $this->assign('p_source', XiangmuModel::getPsource());
        $this->assign('three_level', XiangmuModel::getThreeLevel());
        $this->assign('grade_type', ProjectModel::getGrade());
        return $this->fetch('form');
    }

    public function read($id = 0)
    {
        $row = XiangmuModel::where('id', $id)->find()->toArray();
        if ($row) {
            if (!empty($row['attachment'])){
                $attachment = explode(',',$row['attachment']);
                $row['attachment_show'] = array_filter($attachment);
            }
        }
        $this->assign('data_info', $row);
        $this->assign('subject_option', XiangmuModel::getCat());
        return $this->fetch();
    }
}